### ISSUE TITLE
Upgrade to Istio 1.17

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/node-microservices-demo#32]
The latest Istio has [updated their support for the Gateway API](https://istio.io/latest/news/releases/1.17.x/announcing-1.17/#upgraded-support-for-the-kubernetes-gateway-api), and [support is now in beta](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/). Need to upgrade so we can kick the tires on this.

The upgrade process is currently:
* [Download the latest istioctl](https://istio.io/latest/docs/setup/getting-started/#download)
* run `make upgrade-istio`
* run `make upgrade-istio-operator`
* Stand up the demo in minikube to ensure it works.
* commit the result

**Comment by LilaKelland** [comment]
Closed with PR #35
